# Site
name: "Risk and Resilience DAT/Artathon"
title: "Risk and Resilience DAT/Artathon"
description: "A collaborative and constructive experience to create disaster data art, share skills, and co-develop criteria for visualizing risk data."
logo: 'assets/images/datartathon/logo.png'
favicon: 'assets/images/datartathon/logo.png'
# baseurl: /s
google_analytics: G-FCLD835072
disqus: 'datartathon'
mailchimp-list: 'https://datartathon.us1.list-manage.com/subscribe/post?u=a8947407d3f635f9417d9eb0f&amp;id=8d0ee3f9d9'
include: ["_pages"]
permalink: /:title/
email: datartathon@gmail.com
categories: [Events, News]
port: 3000

# Authors -- these are all the people who have contributed to the website
authors:
  sabine:
    name: Sabine
    display_name: Sabine
    avatar: assets/images/datartathon/sabine_edited.jpg
    email: sloos@usgs.gov
    web: http://datartathon.com/fellows/sabine
    twitter: https://twitter.com/sab_loos
    description: ""
  arogya:
    name: Arogya
    display_name: Arogya
    avatar: assets/images/datartathon/arogya_edited.jpg
    email: arogya.koirala@kathmandulivinglabs.org
    web: http://datartathon.com/fellows/arogya
    twitter: https://twitter.com/koiralaaaa
    description: ""
  muhammad:
    name: Muhammad
    display_name: Muhammad
    avatar: assets/images/datartathon/muhammad.jpg
    web: http://datartathon.com/fellows/muhammad
    twitter: https://twitter.com/Muhamma28397035
    description: ""
  yolanda:
    name: Yolanda
    display_name: Yolanda
    avatar: assets/images/datartathon/yolanda_edited.jpeg
    email: ycl@unm.edu
    web: http://datartathon.com/fellows/yolanda
    twitter: https://twitter.com/DisasterYolanda
    description: ""
  haley:
    name: Haley
    display_name: Haley
    avatar: assets/images/datartathon/haley.png
    web: http://datartathon.com/fellows/haley
    description: ""
  hannah:
    name: Hannah
    display_name: Hannah
    avatar: assets/images/datartathon/hannah.jpg
    twitter: https://twitter.com/hannahmelrea
    web: http://datartathon.com/fellows/hannah
    description: ""
  jackie:
    name: Jackie
    display_name: Jackie
    avatar: assets/images/datartathon/jackie.jpg
    web: http://datartathon.com/fellows/jackie
    description: ""
  daniel:
    name: Daniel
    display_name: Daniel
    avatar: assets/images/datartathon/daniel.png
    web: http://datartathon.com/fellows/daniel
    description: ""
  charlotte:
    name: Charlotte
    display_name: Charlotte
    avatar: assets/images/datartathon/charlotte.jpg
    web: http://datartathon.com/fellows/charlotte
  jorge:
    name: Jorge
    display_name: Jorge
    avatar: assets/images/datartathon/jorge.jpg
    twitter: https://twitter.com/JorgeMarioLR
    web: http://datartathon.com/fellows/jorge
    description: ""

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


      
collections:
  blogs:
    output: true
    permalink: /:collection/:name
    archive: true
  fellows:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# theme: jekyll-theme-cayman
