# Site
name: "Risk and Resilience DAT/Artathon"
title: "Risk and Resilience DAT/Artathon"
description: "A collaborative and constructive experience to create disaster data art, share skills, and co-develop criteria for visualizing risk data."
logo: 'assets/images/datartathon/logo.png'
favicon: 'assets/images/datartathon/logo.png'
# baseurl: /s
google_analytics: 'G-R16EKV4CWS'
disqus: 'datartathon'
mailchimp-list: 'https://datartathon.us1.list-manage.com/subscribe/post?u=a8947407d3f635f9417d9eb0f&amp;id=8d0ee3f9d9'
include: ["_pages"]
permalink: /:title/
email: datartathon@gmail.com
categories: [Events, News]
port: 3000

# Authors
authors:
  sabine:
    name: Sabine
    display_name: Sabine
    gravatar: ff431142425c5ecdaaec6fae52db80e1
    email: sloos@stanford.edu
    web: http://datartathon.com/fellows/sabine
    twitter: https://twitter.com/sab_loos
    description: ""
  arogya:
    name: Arogya
    display_name: Arogya
    gravatar: bffa206f56df3b9138419b6228ad37bc
    email: arogya.koirala@kathmandulivinglabs.org
    web: http://datartathon.com/fellows/arogya
    twitter: https://twitter.com/koiralaaaa
    description: ""
  yolanda:
    name: Yolanda
    display_name: Yolanda
    gravatar: 3f7082f57b6d1055bd190defb4d58b37
    email: ycl@unm.edu
    web: http://datartathon.com/fellows/yolanda
    twitter: https://twitter.com/DisasterYolanda
    description: ""


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


      
collections:
  blogs:
    output: true
    permalink: /:collection/:name
    archive: true
  fellows:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# theme: jekyll-theme-cayman
